NACE_Sector                   <- function(x){
  x[, "NACE"] <- x[, "NACEBEL_SUBSECTOR_OMS"]
  x[, "NACE"] <- gsub("\\s+","",x[, "NACE"])
  x[, "NACE"] <- tolower(x[, "NACE"])
  x[, "NACE"] <- gsub(",","",x[, "NACE"])
  x[, "NACE"] <- gsub("[^[:alpha:] ]","",x[, "NACE"])
  x[, "NACE"] <- gsub("u0096","",x[, "NACE"])
  x[, "NACE"][which(x[, "NACE"] =="accommodation")] <- "I"
  x[, "NACE"][which(x[, "NACE"] =="activitiesauxiliarytofinancialservicesandinsuranceactivities")] <- "K"
  x[, "NACE"][which(x[, "NACE"] =="activitiesofextraterritorialorganisationsandbodies")] <- "U"
  x[, "NACE"][which(x[, "NACE"] =="activitiesofheadofficesmanagementconsultancyactivities")] <- "M"
  x[, "NACE"][which(x[, "NACE"] =="activitiesofhouseholdsasemployersofdomesticpersonnel")] <- "T"
  x[, "NACE"][which(x[, "NACE"] =="activitiesofmembershiporganisations")] <- "S"
  x[, "NACE"][which(x[, "NACE"] =="advertisingandmarketresearch")] <- "M"
  x[, "NACE"][which(x[, "NACE"] =="airtransport")] <- "H"
  x[, "NACE"][which(x[, "NACE"] =="architecturalandengineeringactivitiestechnicaltestingandanalysis")] <- "M"
  x[, "NACE"][which(x[, "NACE"] =="civilengineering")] <- "F"
  x[, "NACE"][which(x[, "NACE"] =="computerprogrammingconsultancyandrelatedactivities")] <- "J"
  x[, "NACE"][which(x[, "NACE"] =="constructionofbuildingsdevelopmentofbuildingprojects")] <- "F"
  x[, "NACE"][which(x[, "NACE"] =="creativeartsandentertainmentactivities")] <- "R"
  x[, "NACE"][which(x[, "NACE"] =="cropsandanimalproductionhuntingandrelatedserviceactivities")] <- "A"
  x[, "NACE"][which(x[, "NACE"] =="education")] <- "P"
  x[, "NACE"][which(x[, "NACE"] =="electricitygassteamandairconditioningsupply")] <- "D"
  x[, "NACE"][which(x[, "NACE"] =="employmentactivities")] <- "N"
  x[, "NACE"][which(x[, "NACE"] =="financialserviceactivitiesexceptinsuranceandpensionfunding")] <- "K"
  x[, "NACE"][which(x[, "NACE"] =="fishingandaquaculture")] <- "A"
  x[, "NACE"][which(x[, "NACE"] =="foodandbeverageserviceactivities")] <- "I"
  x[, "NACE"][which(x[, "NACE"] =="forestryandlogging")] <- "A"
  x[, "NACE"][which(x[, "NACE"] =="gamblingandbettingactivities")] <- "R"
  x[, "NACE"][which(x[, "NACE"] =="humanhealthactivities")] <- "Q"
  x[, "NACE"][which(x[, "NACE"] =="informationserviceactivities")] <- "J"
  x[, "NACE"][which(x[, "NACE"] =="insurancereinsuranceandpensionfundingexceptcompulsorysocialsecurity")] <- "K"
  x[, "NACE"][which(x[, "NACE"] =="landtransportandtransportviapipelines")] <- "H"
  x[, "NACE"][which(x[, "NACE"] =="legalaccountingactivities")] <- "M"
  x[, "NACE"][which(x[, "NACE"] =="librariesarchivesmuseumsandotherculturalactivities")] <- "R"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofbasicmetals")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofbasicpharmaceuticalproductsandpharmaceuticalpreparations")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofbeverages")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofchemicalandchemicalproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofcokeandrefinedpetroleumproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofcomputerelectronicandopticalproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofelectricalequipment")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureoffabricatedmetalproductsexceptmachineryandequipment")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureoffoodsproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureoffurniture")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofleatherandrelatedproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofmachineryandequipment")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofmotorvehiclestrailersandsemitrailers")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofothernonmetallicmineralproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofothertransportequipment")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofpaperandpaperproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofrubberandplasticproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureoftextiles")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureoftobaccoproducts")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofwearingapparel")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="manufactureofwoodandofproductsofwoodandcorkexceptfurnituremanufactureofarticlesofstrawandplaitingmaterials")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="miningofmetalores")] <- "B"
  x[, "NACE"][which(x[, "NACE"] =="miningsupportactivities")] <- "B"
  x[, "NACE"][which(x[, "NACE"] =="motionpicturevideoandtelevisionprogrammeproductionsoundandrecordingandmusicpublishingactivities")] <- "J"
  x[, "NACE"][which(x[, "NACE"] =="officeadministrativeofficesupportandotherbusinesssupportactivities")] <- "N"
  x[, "NACE"][which(x[, "NACE"] =="othermanufacturing")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="otherminingandquarrying")] <- "B"
  x[, "NACE"][which(x[, "NACE"] =="otherpersonalserviceactivities")] <- "S"
  x[, "NACE"][which(x[, "NACE"] =="otherprofessionalscientificandtechnicalactivities")] <- "M"
  x[, "NACE"][which(x[, "NACE"] =="postalandcouriersactivities")] <- "H"
  x[, "NACE"][which(x[, "NACE"] =="printingandreproductionofrecordedmedia")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="programmingandbroadcastingactivities")] <- "J"
  x[, "NACE"][which(x[, "NACE"] =="publicadministrationanddefencecompulsorysocialsecurity")] <- "O"
  x[, "NACE"][which(x[, "NACE"] =="publishingactivities")] <- "J"
  x[, "NACE"][which(x[, "NACE"] =="realestateactivities")] <- "L"
  x[, "NACE"][which(x[, "NACE"] =="remediationactivitiesandotherwastemanagementservices")] <- "E"
  x[, "NACE"][which(x[, "NACE"] =="rentalandleasingactivities")] <- "N"
  x[, "NACE"][which(x[, "NACE"] =="repairandinstallationofmachineryandequipment")] <- "C"
  x[, "NACE"][which(x[, "NACE"] =="repairofcomputersandpersonalandhouseholdsgoods")] <- "S"
  x[, "NACE"][which(x[, "NACE"] =="residentialcareactivities")] <- "Q"
  x[, "NACE"][which(x[, "NACE"] =="retailtradeexceptofmotorvehiclesandmotorcycles")] <- "G"
  x[, "NACE"][which(x[, "NACE"] =="scientificresearchanddevelopment")] <- "M"
  x[, "NACE"][which(x[, "NACE"] =="securityandinvestigationactivities")] <- "N"
  x[, "NACE"][which(x[, "NACE"] =="servicestobuildingsandlandscapeactivities")] <- "N"
  x[, "NACE"][which(x[, "NACE"] =="sewage")] <- "E"
  x[, "NACE"][which(x[, "NACE"] =="socialworkactivitieswithoutaccommodations")] <- "Q"
  x[, "NACE"][which(x[, "NACE"] =="specialisedconstructionactivities")] <- "F"
  x[, "NACE"][which(x[, "NACE"] =="sportsactivitiesandamusementsandrecreationactivities")] <- "R"
  x[, "NACE"][which(x[, "NACE"] =="telecommunications")] <- "J"
  x[, "NACE"][which(x[, "NACE"] =="travelagencytouroperatorreservationserviceandrelatedactivities")] <- "N"
  x[, "NACE"][which(x[, "NACE"] =="undifferentiatedgoodsandservicesproducingactivitiesofprivatehouseholdsforownuse")] <- "T"
  x[, "NACE"][which(x[, "NACE"] =="veterinaryactivities")] <- "M"
  x[, "NACE"][which(x[, "NACE"] =="warehousingandsupportactivitiestotransportation")] <- "H"
  x[, "NACE"][which(x[, "NACE"] =="wastecollectiontreatmentanddisposalactivitiesmaterialrecovery")] <- "E"
  x[, "NACE"][which(x[, "NACE"] =="watercollectiontreatmentandsupply")] <- "E"
  x[, "NACE"][which(x[, "NACE"] =="watertransport")] <- "H"
  x[, "NACE"][which(x[, "NACE"] =="wholesaleandretailtradeandrepairofmotorvehiclesandmotorcycles")] <- "G"
  x[, "NACE"][which(x[, "NACE"] =="wholesaletradeexceptofmotorvehiclesandmotorcycles")] <- "G"
  x

}
